"""
Integration tests for productmd CLI tools.

These tests run inside a container with access to:
  - httpserver: serves a v1.2 compose at HTTP_BASE_URL
  - registry: OCI registry at REGISTRY_URL (seeded with test artifacts)

Run via:  ./tests/integration/run.sh

These tests are NOT discovered by unit test runners (tox/pytest) since
they live in tests/integration/ and require the Docker Compose services.

All CLI inputs must be local files or directories. Tests download
metadata from the HTTP server to local temp directories first, then
pass local paths to the CLI commands.
"""

import json
import os
import subprocess
import tempfile
import urllib.request


HTTP_BASE_URL = os.environ.get("HTTP_BASE_URL", "http://localhost:8080")
REGISTRY_URL = os.environ.get("REGISTRY_URL", "localhost:5000")

# Metadata files available on the HTTP server
METADATA_FILES = ["composeinfo.json", "images.json", "rpms.json", "extra_files.json"]

# v2.0 OCI metadata files generated by registry-seed with real digests.
# Served at {HTTP_BASE_URL}/oci-metadata/<filename>
OCI_METADATA_FILES = ["images-oci.json", "images-mixed.json", "rpms-oci.json", "extra_files-oci.json"]


def _run_productmd(*args):
    """Run a productmd CLI command and return the CompletedProcess."""
    return subprocess.run(
        ["productmd"] + list(args),
        capture_output=True,
        text=True,
    )


def _download_metadata(dest_dir):
    """Download metadata files from the HTTP server to a local directory.

    Creates a compose-like layout: dest_dir/metadata/*.json
    """
    metadata_dir = os.path.join(dest_dir, "metadata")
    os.makedirs(metadata_dir, exist_ok=True)

    for filename in METADATA_FILES:
        url = f"{HTTP_BASE_URL}/metadata/{filename}"
        dest = os.path.join(metadata_dir, filename)
        try:
            urllib.request.urlretrieve(url, dest)
        except urllib.error.URLError:
            pass  # Some files may not exist (e.g., modules.json)

    return dest_dir


ARTIFACT_PATHS = [
    "Server/x86_64/iso/boot.iso",
    "Server/x86_64/os/GPL",
    "Server/x86_64/os/Packages/b/bash-5.2.26-3.fc41.x86_64.rpm",
    "Server/aarch64/iso/boot.iso",
    "Server/aarch64/os/GPL",
    "Server/aarch64/os/Packages/b/bash-5.2.26-3.fc41.aarch64.rpm",
]


def _download_compose(dest_dir):
    """Download the full compose (metadata + artifacts) from the HTTP server.

    Creates a proper compose layout::

        dest_dir/
          metadata/
            composeinfo.json
            images.json
            rpms.json
            extra_files.json
          Server/
            x86_64/
              iso/boot.iso
              os/...
            aarch64/
              iso/boot.iso
              os/...
    """
    _download_metadata(dest_dir)

    for rel_path in ARTIFACT_PATHS:
        url = f"{HTTP_BASE_URL}/{rel_path}"
        dest = os.path.join(dest_dir, rel_path)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        try:
            urllib.request.urlretrieve(url, dest)
        except urllib.error.URLError:
            pass

    return dest_dir


def _download_oci_metadata(dest_dir, files=None):
    """Download generated v2.0 OCI metadata from the HTTP server.

    These files are generated by the registry-seed container with real
    OCI digests and served at /oci-metadata/*.json by the HTTP server.

    Downloads to dest_dir/<filename> (flat, not in a metadata/ subdir).
    """
    os.makedirs(dest_dir, exist_ok=True)
    for filename in files or OCI_METADATA_FILES:
        url = f"{HTTP_BASE_URL}/oci-metadata/{filename}"
        dest = os.path.join(dest_dir, filename)
        urllib.request.urlretrieve(url, dest)
    return dest_dir


class TestUpgradeIntegration:
    """Test upgrading a v1.2 compose to v2.0 via the CLI."""

    def test_upgrade_compose_dir(self):
        """Upgrade a v1.2 compose directory to v2.0."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)
            output_dir = os.path.join(tmp_dir, "v2")

            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                compose_dir,
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            # Verify v2.0 output exists
            images_path = os.path.join(output_dir, "images.json")
            assert os.path.isfile(images_path)

            with open(images_path) as f:
                data = json.load(f)
            assert data["header"]["version"] == "2.0"

            # URLs should point to HTTP server
            for variant in data["payload"]["images"]:
                for arch in data["payload"]["images"][variant]:
                    for img in data["payload"]["images"][variant][arch]:
                        assert img["location"]["url"].startswith(HTTP_BASE_URL)

    def test_upgrade_single_file(self):
        """Upgrade a single metadata file to v2.0."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)
            output_dir = os.path.join(tmp_dir, "v2")

            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"
            assert os.path.isfile(os.path.join(output_dir, "images.json"))

    def test_upgrade_with_compute_checksums(self):
        """Upgrade with --compute-checksums populates checksum fields."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            # Download full compose (metadata + artifacts)
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_compose(compose_dir)

            output_dir = os.path.join(tmp_dir, "v2-checksums")
            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                "--compute-checksums",
                compose_dir,
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

    def test_upgrade_multiple_metadata_files(self):
        """Upgrade produces output for all available metadata types."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)
            output_dir = os.path.join(tmp_dir, "v2")

            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                compose_dir,
            )

            assert result.returncode == 0
            assert os.path.isfile(os.path.join(output_dir, "images.json"))
            assert os.path.isfile(os.path.join(output_dir, "rpms.json"))

    def test_upgrade_url_rejected(self):
        """Test that remote URLs are rejected."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            result = _run_productmd(
                "upgrade",
                "--output",
                os.path.join(tmp_dir, "v2"),
                "--base-url",
                f"{HTTP_BASE_URL}/",
                HTTP_BASE_URL,
            )
            assert result.returncode == 1
            assert "Remote URLs are not supported" in result.stderr

    def test_upgrade_base_url_without_trailing_slash(self):
        """Test that base URL without trailing slash is normalized."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)
            output_dir = os.path.join(tmp_dir, "v2")

            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                HTTP_BASE_URL,  # no trailing slash
                compose_dir,
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            with open(os.path.join(output_dir, "images.json")) as f:
                data = json.load(f)

            for variant in data["payload"]["images"]:
                for arch in data["payload"]["images"][variant]:
                    for img in data["payload"]["images"][variant][arch]:
                        url = img["location"]["url"]
                        # Should be properly joined, not "http://...Server/..."
                        assert "/Server/" in url or "/Workstation/" in url
                        assert f"{HTTP_BASE_URL}Server" not in url

    def test_upgrade_strict_checksums(self):
        """Test --strict-checksums with a real compose."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            # Download full compose (metadata + artifacts)
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_compose(compose_dir)

            output_dir = os.path.join(tmp_dir, "v2-strict")
            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                "--strict-checksums",
                compose_dir,
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            with open(os.path.join(output_dir, "images.json")) as f:
                data = json.load(f)
            assert data["header"]["version"] == "2.0"

            # All images should have checksums
            for variant in data["payload"]["images"]:
                for arch in data["payload"]["images"][variant]:
                    for img in data["payload"]["images"][variant][arch]:
                        assert img["location"]["checksum"] is not None
                        assert img["location"]["checksum"].startswith("sha256:")

    def test_upgrade_non_compose_dir_errors(self):
        """Test that passing a non-compose directory errors."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            empty_dir = os.path.join(tmp_dir, "not-a-compose")
            os.makedirs(empty_dir)

            result = _run_productmd(
                "upgrade",
                "--output",
                os.path.join(tmp_dir, "v2"),
                "--base-url",
                "https://cdn/",
                empty_dir,
            )

            assert result.returncode == 1
            assert "compose" in result.stderr.lower() or "metadata" in result.stderr.lower()

    def test_upgrade_single_file_discovers_compose_root(self):
        """Test that --compute-checksums works with a single file inside a compose."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            # Download the full compose (metadata + artifacts) to create
            # a proper local compose layout for checksum computation.
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_compose(compose_dir)

            # Upgrade a single file from inside the compose with
            # --compute-checksums. The tool should discover the compose
            # root from the file's location in metadata/.
            output_dir = os.path.join(tmp_dir, "v2")
            result = _run_productmd(
                "upgrade",
                "--output",
                output_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                "--compute-checksums",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            with open(os.path.join(output_dir, "images.json")) as f:
                data = json.load(f)

            # Checksums should be computed since compose root was discovered
            for variant in data["payload"]["images"]:
                for arch in data["payload"]["images"][variant]:
                    for img in data["payload"]["images"][variant][arch]:
                        assert img["location"]["checksum"] is not None
                        assert img["location"]["checksum"].startswith("sha256:")


class TestDowngradeIntegration:
    """Test downgrading v2.0 metadata to v1.2 via the CLI."""

    def test_downgrade_from_upgraded(self):
        """Upgrade to v2.0 then downgrade back to v1.2."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            v1_dir = os.path.join(tmp_dir, "v1")

            # Step 1: Upgrade
            _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            # Step 2: Downgrade
            result = _run_productmd(
                "downgrade",
                "--output",
                v1_dir,
                os.path.join(v2_dir, "images.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            images_path = os.path.join(v1_dir, "images.json")
            assert os.path.isfile(images_path)

            with open(images_path) as f:
                data = json.load(f)
            assert data["header"]["version"] == "1.2"

            for variant in data["payload"]["images"]:
                for arch in data["payload"]["images"][variant]:
                    for img in data["payload"]["images"][variant][arch]:
                        assert "path" in img
                        assert "location" not in img


class TestLocalizeIntegration:
    """Test localizing a distributed compose via HTTP downloads."""

    def test_localize_from_http(self):
        """Upgrade then localize: download artifacts from HTTP server."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            local_dir = os.path.join(tmp_dir, "local")

            # Step 1: Upgrade
            _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            # Step 2: Localize
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "2",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"
            assert "Downloaded:" in result.stdout

    def test_localize_creates_files(self):
        """Localize creates the expected file structure."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            local_dir = os.path.join(tmp_dir, "local")

            _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )

            compose_root = os.path.join(local_dir, "compose")
            iso_path = os.path.join(compose_root, "Server", "x86_64", "iso", "boot.iso")
            assert os.path.isfile(iso_path), f"Expected {iso_path} to exist"

            metadata_dir = os.path.join(compose_root, "metadata")
            assert os.path.isfile(os.path.join(metadata_dir, "images.json"))

    def test_localize_skip_existing(self):
        """Test --skip-existing skips already-downloaded files on second run."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            local_dir = os.path.join(tmp_dir, "local")

            _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            # First download
            _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )

            # Second download with --skip-existing
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--skip-existing",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )

            assert result.returncode == 0
            assert "Skipped:" in result.stdout


class TestVerifyIntegration:
    """Test verifying compose integrity via the CLI."""

    def test_verify_quick_mode(self):
        """Test --quick only verifies metadata loads."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            result = _run_productmd(
                "verify",
                "--quick",
                compose_dir,
            )

            assert result.returncode == 0
            assert "Quick mode" in result.stdout

    def test_verify_with_report(self):
        """Test --report writes a JSON report file."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)
            report_file = os.path.join(tmp_dir, "report.json")

            _run_productmd(
                "verify",
                "--quick",
                "--report",
                report_file,
                compose_dir,
            )

            assert os.path.isfile(report_file)
            with open(report_file) as f:
                report = json.load(f)
            assert "verified" in report
            assert "failed" in report
            assert "skipped" in report


class TestRpmsRoundTripIntegration:
    """Test round-trip with RPMs metadata (not just images)."""

    def test_rpms_upgrade_localize_downgrade(self):
        """Round-trip rpms.json: upgrade -> localize -> downgrade."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            local_dir = os.path.join(tmp_dir, "local")
            v1_dir = os.path.join(tmp_dir, "v1")

            # Upgrade rpms.json
            result = _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "rpms.json"),
            )
            assert result.returncode == 0

            # Localize RPMs
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "rpms.json"),
            )
            assert result.returncode == 0

            # Verify RPM file was downloaded
            rpm_path = os.path.join(
                local_dir,
                "compose",
                "Server",
                "x86_64",
                "os",
                "Packages",
                "b",
                "bash-5.2.26-3.fc41.x86_64.rpm",
            )
            assert os.path.isfile(rpm_path), f"Expected {rpm_path} to exist"

            # Downgrade back to v1.2
            result = _run_productmd(
                "downgrade",
                "--output",
                v1_dir,
                os.path.join(v2_dir, "rpms.json"),
            )
            assert result.returncode == 0

            with open(os.path.join(v1_dir, "rpms.json")) as f:
                data = json.load(f)
            assert data["header"]["version"] == "1.2"


class TestLocalizeContentVerification:
    """Test that localized artifact content matches the original."""

    def test_localize_file_content_matches(self):
        """Verify downloaded file content matches the fixture."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            local_dir = os.path.join(tmp_dir, "local")

            _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )

            _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )

            # Read the downloaded file
            iso_path = os.path.join(
                local_dir,
                "compose",
                "Server",
                "x86_64",
                "iso",
                "boot.iso",
            )
            with open(iso_path) as f:
                content = f.read()

            # Should match the fixture content served by the HTTP server
            assert "FAKE ISO CONTENT FOR INTEGRATION TESTING" in content


class TestDowngradeComposeDirIntegration:
    """Test downgrade with compose directory input."""

    def test_downgrade_compose_dir(self):
        """Downgrade a compose directory."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            v1_dir = os.path.join(tmp_dir, "v1")

            # Upgrade all metadata
            _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                compose_dir,
            )

            # Localize to create a compose layout with metadata
            local_dir = os.path.join(tmp_dir, "local")
            _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )

            # Downgrade using -c on the localized compose
            localized_compose = os.path.join(local_dir, "compose")
            result = _run_productmd(
                "downgrade",
                "--output",
                v1_dir,
                localized_compose,
            )

            assert result.returncode == 0
            assert os.path.isfile(os.path.join(v1_dir, "images.json"))

            with open(os.path.join(v1_dir, "images.json")) as f:
                data = json.load(f)
            assert data["header"]["version"] == "1.2"


class TestVerifyAfterLocalizeIntegration:
    """Test verify after localize with computed checksums."""

    def test_verify_localized_compose_with_checksums(self):
        """Upgrade with checksums, then verify the compose passes."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            # Download full compose (metadata + artifacts)
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_compose(compose_dir)

            # Step 1: Upgrade with --compute-checksums
            v2_dir = os.path.join(tmp_dir, "v2")
            result = _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                "--compute-checksums",
                compose_dir,
            )
            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            # Step 2: Copy the checksummed v2.0 metadata into the compose
            # so verify can find both the metadata and the artifacts.
            import shutil

            metadata_dir = os.path.join(compose_dir, "metadata")
            for fname in os.listdir(v2_dir):
                if fname.endswith(".json"):
                    shutil.copy2(
                        os.path.join(v2_dir, fname),
                        os.path.join(metadata_dir, fname),
                    )

            # Step 3: Verify — checksums computed from the same files
            result = _run_productmd(
                "verify",
                compose_dir,
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"
            assert "Verified:" in result.stdout


class TestLocalizeOciIntegration:
    """Test localizing artifacts from the OCI registry.

    Uses v2.0 metadata generated by the registry-seed container
    with real OCI digests pointing to the test registry.
    """

    def test_localize_single_oci_image(self):
        """Download a single OCI artifact from the registry."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["images-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")

            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                os.path.join(oci_dir, "images-oci.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"
            assert "Downloaded:" in result.stdout

            # Verify the ISO was downloaded
            iso_path = os.path.join(local_dir, "compose", "Server", "x86_64", "iso", "boot.iso")
            assert os.path.isfile(iso_path), f"Expected {iso_path} to exist"

    def test_localize_parallel_oci_downloads(self):
        """Download multiple OCI artifacts in parallel."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["images-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")

            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "2",
                "--no-verify-checksums",
                os.path.join(oci_dir, "images-oci.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            # Both arches should be downloaded
            x86_iso = os.path.join(local_dir, "compose", "Server", "x86_64", "iso", "boot.iso")
            aarch64_iso = os.path.join(local_dir, "compose", "Server", "aarch64", "iso", "boot.iso")
            assert os.path.isfile(x86_iso), f"Expected {x86_iso} to exist"
            assert os.path.isfile(aarch64_iso), f"Expected {aarch64_iso} to exist"

    def test_localize_mixed_http_and_oci(self):
        """Download a compose with both HTTP and OCI URLs."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["images-mixed.json"])
            local_dir = os.path.join(tmp_dir, "local")

            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "2",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(oci_dir, "images-mixed.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            # x86_64 (HTTP) and aarch64 (OCI) should both be present
            x86_iso = os.path.join(local_dir, "compose", "Server", "x86_64", "iso", "boot.iso")
            aarch64_iso = os.path.join(local_dir, "compose", "Server", "aarch64", "iso", "boot.iso")
            assert os.path.isfile(x86_iso), f"Expected {x86_iso} to exist"
            assert os.path.isfile(aarch64_iso), f"Expected {aarch64_iso} to exist"

    def test_localize_oci_skip_existing(self):
        """Test --skip-existing works for OCI downloads."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["images-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")

            # First download
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                os.path.join(oci_dir, "images-oci.json"),
            )
            assert result.returncode == 0

            # Second download with --skip-existing
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                "--skip-existing",
                os.path.join(oci_dir, "images-oci.json"),
            )

            assert result.returncode == 0
            assert "Skipped:" in result.stdout

    def test_localize_oci_content_matches(self):
        """Verify downloaded OCI artifact content matches the fixture."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["images-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")

            _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                os.path.join(oci_dir, "images-oci.json"),
            )

            # The downloaded boot.iso should contain the fixture text
            iso_path = os.path.join(local_dir, "compose", "Server", "x86_64", "iso", "boot.iso")
            with open(iso_path) as f:
                content = f.read()
            assert "FAKE ISO CONTENT FOR INTEGRATION TESTING" in content

    def test_localize_oci_rpms(self):
        """Download RPMs from the OCI registry."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["rpms-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")

            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "2",
                "--no-verify-checksums",
                os.path.join(oci_dir, "rpms-oci.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            x86_rpm = os.path.join(
                local_dir,
                "compose",
                "Server",
                "x86_64",
                "os",
                "Packages",
                "b",
                "bash-5.2.26-3.fc41.x86_64.rpm",
            )
            aarch64_rpm = os.path.join(
                local_dir,
                "compose",
                "Server",
                "aarch64",
                "os",
                "Packages",
                "b",
                "bash-5.2.26-3.fc41.aarch64.rpm",
            )
            assert os.path.isfile(x86_rpm), f"Expected {x86_rpm} to exist"
            assert os.path.isfile(aarch64_rpm), f"Expected {aarch64_rpm} to exist"

    def test_localize_oci_extra_files(self):
        """Download extra files from the OCI registry."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["extra_files-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")

            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                os.path.join(oci_dir, "extra_files-oci.json"),
            )

            assert result.returncode == 0, f"stdout: {result.stdout}\nstderr: {result.stderr}"

            gpl_x86 = os.path.join(local_dir, "compose", "Server", "x86_64", "os", "GPL")
            gpl_aarch64 = os.path.join(local_dir, "compose", "Server", "aarch64", "os", "GPL")
            assert os.path.isfile(gpl_x86), f"Expected {gpl_x86} to exist"
            assert os.path.isfile(gpl_aarch64), f"Expected {gpl_aarch64} to exist"

    def test_localize_oci_downgrade_roundtrip(self):
        """Localize OCI images then downgrade to v1.2."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            oci_dir = os.path.join(tmp_dir, "oci-metadata")
            _download_oci_metadata(oci_dir, ["images-oci.json"])
            local_dir = os.path.join(tmp_dir, "local")
            v1_dir = os.path.join(tmp_dir, "v1")

            # Step 1: Localize from OCI
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "1",
                "--no-verify-checksums",
                os.path.join(oci_dir, "images-oci.json"),
            )
            assert result.returncode == 0

            # Step 2: Downgrade the OCI metadata to v1.2
            result = _run_productmd(
                "downgrade",
                "--output",
                v1_dir,
                os.path.join(oci_dir, "images-oci.json"),
            )
            assert result.returncode == 0

            with open(os.path.join(v1_dir, "images.json")) as f:
                data = json.load(f)
            assert data["header"]["version"] == "1.2"

            # v1.2 should have path, not location, and no oci:// URLs
            for variant in data["payload"]["images"]:
                for arch in data["payload"]["images"][variant]:
                    for img in data["payload"]["images"][variant][arch]:
                        assert "path" in img
                        assert "location" not in img
                        assert not img["path"].startswith("oci://")


class TestRoundTripIntegration:
    """Test full round-trip: v1.2 -> v2.0 -> localize -> downgrade -> compare."""

    def test_full_round_trip(self):
        """Full round-trip preserves compose structure."""
        with tempfile.TemporaryDirectory() as tmp_dir:
            compose_dir = os.path.join(tmp_dir, "compose")
            _download_metadata(compose_dir)

            v2_dir = os.path.join(tmp_dir, "v2")
            local_dir = os.path.join(tmp_dir, "local")
            v1_dir = os.path.join(tmp_dir, "v1-downgraded")

            # Step 1: Upgrade to v2.0
            result = _run_productmd(
                "upgrade",
                "--output",
                v2_dir,
                "--base-url",
                f"{HTTP_BASE_URL}/",
                os.path.join(compose_dir, "metadata", "images.json"),
            )
            assert result.returncode == 0

            # Step 2: Localize (download)
            result = _run_productmd(
                "localize",
                "--output",
                local_dir,
                "--parallel-downloads",
                "2",
                "--no-verify-checksums",
                "--retries",
                "1",
                os.path.join(v2_dir, "images.json"),
            )
            assert result.returncode == 0

            # Step 3: Downgrade back to v1.2
            localized_compose = os.path.join(local_dir, "compose")
            result = _run_productmd(
                "downgrade",
                "--output",
                v1_dir,
                localized_compose,
            )
            assert result.returncode == 0

            # Step 4: Verify v1.2 output has correct paths
            with open(os.path.join(v1_dir, "images.json")) as f:
                data = json.load(f)

            assert data["header"]["version"] == "1.2"

            images = data["payload"]["images"]
            for variant in images:
                for arch in images[variant]:
                    for img in images[variant][arch]:
                        assert "path" in img
                        assert "location" not in img
                        assert not img["path"].startswith("http")


class TestCliEntryPoint:
    """Test the productmd CLI entry point itself."""

    def test_no_subcommand_shows_help(self):
        """Running productmd without a subcommand shows help."""
        result = _run_productmd()
        assert result.returncode != 0

    def test_help_flag(self):
        """Running productmd --help shows usage information."""
        result = _run_productmd("--help")
        assert result.returncode == 0
        assert "usage:" in result.stdout.lower() or "productmd" in result.stdout

    def test_subcommand_help(self):
        """Each subcommand supports --help."""
        for cmd in ["upgrade", "downgrade", "localize", "verify"]:
            result = _run_productmd(cmd, "--help")
            assert result.returncode == 0, f"{cmd} --help failed"
