#!/bin/sh


# download all .treeinfo files for Fedora releases


mkdir -p treeinfo

ARCHES="i386 x86_64 ppc ppc64 armhfp"
VARIANTS="Fedora Everything Live Cloud Docker Images Server Workstation"

for rel in $(seq 1 6); do
#    continue
    for arch in $ARCHES; do
        file=treeinfo/fedora-$rel.$arch
        wget https://archives.fedoraproject.org/pub/archive/fedora/linux/core/$rel/$arch/os/.treeinfo -O $file || rm $file
    done
done

for rel in $(seq 7 17); do
#    continue
    for arch in $ARCHES; do
        for variant in $VARIANTS; do
            file=treeinfo/fedora-$rel-$variant.$arch
            wget https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/$rel/$variant/$arch/os/.treeinfo -O $file || rm $file
        done
    done
done

for rel in $(seq 18 21); do
#    continue
    for arch in $ARCHES; do
        for variant in $VARIANTS; do
            file=treeinfo/fedora-$rel-$variant.$arch
            wget http://dl.fedoraproject.org/pub/fedora/linux/releases/$rel/$variant/$arch/os/.treeinfo -O $file || rm $file
        done
    done
done
